remove unecessary colour words, seperate sucess functions

diff --git a/yt-boat b/yt-boat
--- a/yt-boat
+++ b/yt-boat
@@ -1,30 +1,33 @@
 #!/bin/bash
 # Colour variables
-green="\e[1;32m"
-red="\e[1;31m"
-yellow="\e[0;93m"
-reset="\e[0m"
+g="\e[1;32m"
+y="\e[0;93m"
+r="\e[0m"
 
 # File variables
 QF="$XDG_DATA_HOME/yt-boat/yt-boat.queue"
 
 # Functions
 ERR_ () {
-	echo -e "${yellow}yt-boat: Error: ${1:-"Unknown: Please submit an issue or contact me \
-	as this is probably an error with the code itself"}${reset}" 1>&2
+	echo -e "${y}yt-boat: Error: ${1:-"Unknown: Please submit an issue or contact me \
+	as this is probably an error with the code itself"}${r}" 1>&2
 	exit 1
 }
 
-OK_ () {
-	echo -e "${green}${1}${reset}" 1>&2
+OK () {
+	echo -e "${g}$1${r}" 1>&2
+}
+
+OK_EXIT () {
+	echo -e "${g}$1${r}" 1>&2
 	exit 0
 }
 
 QUEUE_ () {
-	echo -e "There are ${green}$(wc -l $QF | cut -c 1)${reset} vidoes in the queue:"
+	echo -e "There are ${g}$(wc -l $QF | cut -c 1)${r} vidoes in the queue:"
 	for i in $(cat $QF)
 	do
-		echo -e "$(yt-dlp -s --no-warnings --ignore-config --print title $i) - $(($(yt-dlp -s --no-warnings --ignore-config --print duration $i) / 60)):$(($(yt-dlp -s --no-warnings --ignore-config --print duration $i) % 60)) ${green}$i${reset}"
+		echo -e "$(yt-dlp -s --no-warnings --ignore-config --print title $i) - $(($(yt-dlp -s --no-warnings --ignore-config --print duration $i) / 60)):$(($(yt-dlp -s --no-warnings --ignore-config --print duration $i) % 60)) ${g}$i${r}"
 	done
 }
 
@@ -55,7 +58,7 @@ while test "$#" -gt 0; do
 				do
 					echo "$i" | grep -o -P "(?:v=|\/embed\/|\/1\/|\/v\/)([^&\n?#]+)" | cut -c 3- >> $QF
 				done
-				OK_ "Videos added to queue" || ERR_
+				OK_EXIT "Videos added to queue" || ERR_
 			;;
 		
 		aa|add-alternative|--add-alternative)
@@ -64,14 +67,14 @@ while test "$#" -gt 0; do
 				do
 					echo $i >> $QF
 				done
-				OK_ "Video added to queue"
+				OK_EXIT "Video added to queue"
 			;;
 
 
 		d|download|--download)
 			if yt-dlp -a "$QF"; then
 				: > $QF
-				OK_ "Videos downloaded"
+				OK_EXIT "Videos downloaded"
 			else
 				ERR_ "Probably unsupported url or invalid format hardcoded in your yt-dlp config"
 			fi
@@ -79,7 +82,7 @@ while test "$#" -gt 0; do
 
 		c|clear|--clear)
 			if : > $QF; then
-				OK_ "Queue cleared"
+				OK_EXIT "Queue cleared"
 			else
 				ERR_
 			fi
@@ -88,7 +91,7 @@ while test "$#" -gt 0; do
 		q|queue|--queue)
 		shift
 			if QUEUE_; then
-				OK_
+				OK_EXIT
 			else
 				ERR_ "Queue file may not exist, see FAQ's"
 			fi
@@ -96,7 +99,7 @@ while test "$#" -gt 0; do
 
 		h|help|--help)
 			if HELP_; then
-				OK_
+				OK_EXIT
 			else
 				ERR_
 			fi
@@ -105,9 +108,9 @@ while test "$#" -gt 0; do
         	-hnb)
 			clear
 			if echo -e "$(HELP_)"; then
-				echo -e "${green}Press enter to go back to newsboat${reset}"
+				OK "Press enter to go back to newsboat"
 				read
-				OK_
+				OK_EXIT
 			else
 				ERR_
 			fi
@@ -116,9 +119,9 @@ while test "$#" -gt 0; do
 		-qnb)
 			clear
 			if echo -e "$(QUEUE_)"; then
-				echo -e "${green}Press enter to go back to newsboat${reset}"
+				OK "Press enter to go back to newsboat"
 				read
-				OK_
+				OK_EXIT
 			else
 				ERR_
 			fi
@@ -126,7 +129,7 @@ while test "$#" -gt 0; do
 
 		*)
 			shift
-			echo -e "${yellow}Not a valid option${reset}"
+			echo -e "${y}Not a valid option${r}"
 			HELP_
 			ERR_
 			;;
